# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
# url: "https://gem-swim.github.io" # the url of your github pages
url: "http://127.0.0.1:4000/" # Local

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Book Lessons
  permalink: book

# use false to turn off any social media links
twitter: false
facebook: https://www.facebook.com/groups/gemswimidaho
instagram: https://www.instagram.com/gemswimidaho/
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Gem Swim"
# footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
