# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
# url: "https://gem-swim.github.io" # the url of your github pages
url: "http://127.0.0.1:4000/" # Local

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# navigation menu
show-nav-menu: true

employees:
- name: Kirsten Clayton
  title: Founder / CEO
  description: Welcome! I am the owner of Gem Swim and mother of 3 girls.
            I am a certified WSI, Survival Swim instructor and swim mom. I am passionate about safety and swimming and
            believe every child should know how to be safe in the water. I LOVE watching kids progress. Nothing beats
            seeing that float for the first time! Thank you for trusting us to teach your kids. I can't wait to see you
            poolside!
  picture: kirsten.jpg
- name: Olivia
  title: Swim Teacher
  description: Hey!! My name is Olivia. I'm currently a lifeguard at the rec center and CPR/AED certified. I love hanging 
            out with kids! My goal this summer is to help your kids become comfortable and have fun in the water!
  picture: liv.jpg
- name: Kaleb
  title: Swim Teacher
  description: Hello! My name is Kaleb. I am currently a member of the Nampa Shark Swim Team and Treasure Valley Water 
            Polo Team. From a young age, I have always loved swimming. I feel it is an important skill for everyone to 
            have. I look forward to meeting you and sharing not just the imporant swimming skills but also how fun it can be!
  picture: kaleb.jpg
- name: Sadie
  title: Swim Teacher
  description: Hello! I love being active and having fun! I am on my high school cross country, track, and swim team. 
            I have also been competitively swimming for 9 years. I am Lifeguard and CPR certified and can't wait to meet 
            your kids and help them feel as comfortable in the water as I am!
  picture: sadie.jpg

faqs:
- question: What should a parent do during lessons if a child is upset?
  answer: Some kids love the water, some kids hate it! The first lessons focus on being comfortable in the water,
    and a lot of that comes from building trust between student and teacher. Parents are required to be at every lesson, 
    but these aren't "mommy and me" classes. Parents do not need to get into the water.
    <br />
    <br />
    Sometimes having a parent in eyesight is helpful to calm a child. but sometimes it makes kids more anxious because
    they just want to be with their mom/dad! We will work together as a team (parent/student/teacher) to come up with 
    the best plan.
- question: I have more than one child that I want lessons for. Can you do small group classes?
  answer: I will not be offering small groups because I want to give each child my undivided attention. 
    However, the lessons are only 20 minutes, and we can do back to back lessons for siblings!
- question: How many lessons does a child typically need and how often should we plan on lessons? Is there a sesson that we need to sign up for?
  answer: The amount of lessons will completely depend on the age/ability of your child. That's why I didn't want to do a 
    rigid swim schedule or a reoccurring weekly session. I recommend planning on at least 10 lessons, ideally 5x a week for 2 weeks to start with,
    but for some kids it can take more. However, I understand that families are busy and that isn't always possible! I want these lessons
    to fit into your life. Since they are lessons specific for each child, there isn't a weekly required swim session you are signing up for. So sign up for as many
    as you are able/willing to do!
- question: How should we prepare for lessons the first day?
  answer: 1. Know Your Schedule! - It's always a good idea to double check the time slots you reserved. These are short lessons
    and the times vary slightly each day.
    <br />
    <br />
    2. Come Early - Please arrive around 5-10 minutes early. You can park in one of the gravel spots in front of the house and please
    be respectful of the neighbors by only parking on the street in front of our house. Ideally, we would also have only one car per family
    to lesson the impact of traffic in our residential neighborhood.
    <br />
    <br />
    3. Have Child Ready - If your child is not potty trained, you MUST have a swim diaper AND a plastic cover. Also, please don't eat 1 hour before the lesson. The last thing
    we want is for a child to have something come back up!
- question: Do you teach regular lessons as well? I want my child to learn different strokes.
  answer: "Yes! If kids are safe in the water, we can go straight to strokes. But remember, survival lessons
    incorporate the beginning stages of swimming, so kids get stroke work from the very beginning!
    We start with back stroke and front stroke and then add an additional strokes if kids want to learn
    more: breast stroke, butterfly, side stroke, elementary backstroke."
- question: What are survival lessons? How are they different from regular lessons?
  answer: These are 1:1 lessons personalized to your child based on ability, child temperament, and learning style. The biggest
    skill for survival is the back float and we emphasize that while also incorporating the beginning
    stages of strokes, starting with the back stroke. 
- question: At what age do you start lessons?
  answer: Lessons can begin as early as 6 months, if developmentally appropriate. Babies need to be able
    to have good head/neck control and be able to sit up. I can teach from 6 months to adults, and anyone in between,
    so there are lessons for everyone!


# use false to turn off any social media links
twitter: false
facebook: https://www.facebook.com/groups/gemswimidaho
instagram: https://www.instagram.com/gemswimidaho/
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Gem Swim"
# footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
